default:
  snap_dir: data/snapdiff/snapshots//
  log_file: data/snapdiff/logs/snapdiff.log
  ignore_unchanged_funcs: true
  mode: snap # diff or snap
  log_to_file: true
  force_config: false

models:
  snap_dir: data/snapdiff/models/
  log_file: data/snapdiff/logs/snapdiff.log
  ignore_unchanged_funcs: true
  log_to_file: false
